name: Docker Image CI

on:
  push:
    branches:
    - master
    - version/*
  pull_request:
    branches:
    - master
    - version/*

env:
  PAPER_VERSION: 1.16.1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build paper version
      env:
        PAPER_VERSION: ${{ env.PAPER_VERSION }}
      run: docker build . --file Dockerfile --tag gonzalotp/paperdocker:${PAPER_VERSION}

    - name: Log into registry
      env:
        SUPER_SECRET: ${{ secrets.REGISTRY_KEY }}
      run: echo ${SUPER_SECRET} | docker login -u gonzalotp --password-stdin

    - name: Push Image
      run: |
        version=$(echo "${GITHUB_REF#refs/*/*/}" | sed -e 's/version\/(.+)/$1/g')
        docker push gonzalotp/paperdocker:${version}
