name: Docker Image CI

on:
  push:
    branches:
    - version/*
  pull_request:
    branches:
    - version/*
  schedule:
    - cron: '0 0 * * *'

env:
  PAPER_VERSION: 1.16.1
  PAPER_BUILD: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build paper version
      env:
        PAPER_VERSION: ${{ env.PAPER_VERSION }}
        PAPER_BUILD: ${{ env.PAPER_BUILD }}
      run: docker build . --build-arg PAPER_VERSION --build-arg PAPER_BUILD --file Dockerfile --tag gonzalotp/paperdocker:${PAPER_VERSION}-${PAPER_BUILD}

    - name: Log into registry
      env:
        SUPER_SECRET: ${{ secrets.REGISTRY_KEY }}
      run: echo ${SUPER_SECRET} | docker login -u gonzalotp --password-stdin

    - name: Push Image
      env:
        PAPER_VERSION: ${{ env.PAPER_VERSION }}
        PAPER_BUILD: ${{ env.PAPER_BUILD }}
      run: docker push gonzalotp/paperdocker:${PAPER_VERSION}-${PAPER_BUILD}
